//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trukov_315_exam.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.MonthlyPayment = new HashSet<MonthlyPayment>();
            this.ProductProdaja = new HashSet<ProductProdaja>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int WorkerID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public System.DateTime DateSdachi { get; set; }
        public double CostOcenoch { get; set; }
        public double SumZaloga { get; set; }
        public double SumVykupa { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyPayment> MonthlyPayment { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductProdaja> ProductProdaja { get; set; }
    }
}
